### PR TITLE
{WIP}(maint) Update the Lingua-Pupuli landing page.

### PR DESCRIPTION
**Pull request by glennsarti**

### CODE REVIEW

**Comment by jpogran** [comment]
looking good!

**Review by jpogran — APPROVED** [review]
i think we can merge this as is!

**Comment by glennsarti** [comment]
Did I really raise this 1 1/2 years ago?!?!

**Comment by glennsarti** [comment]
It's still WIP.  I didn't even know I had this PR open :-)

**Comment by jpogran** [comment]
I thought this was the work for the temp URL your sent me :)

**Pull request closed without merging**
